#!/bin/bash

# WELCOME YOUR EMAILS ABOUT COMMUNICATION AND CONSULTATION 
# AUTHOR: XIAOYANG SUN (xshaun@outlook.com).ALL RIGHTS RESERVED
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.

# Ensure python3 is installed.
# The 'hadoop-build-env.py' script execution relys on python3.
# Note here just check installation path as ubuntu(debian) package rules.
if [[ ! -e /usr/bin/python3 ]]; then 
    echo "Please install python3 and requirements before executing this script;"
    echo "Following commands may be helpful: "
    echo "$ sudo apt-get install python3 && pip3 install -r ./requirements/pip3-requirements.txt"
    exit 
fi

/usr/bin/python3 -B ./hadoop-build-env.py $@

